#pragma once

#define PRODUCT_ID      0x6061
#define DEVICE_VER      0x0002

#define SPACE_CADET_MODIFIER_CARRYOVER
#define LSPO_KEYS KC_LSFT, KC_TRNS, KC_8
#define RSPC_KEYS KC_RSFT, KC_TRNS, KC_9
#define LCPO_KEYS KC_LCTL, KC_LALT, KC_7
#define RCPC_KEYS KC_RCTL, KC_RALT, KC_0

/*
#define PS2_CLOCK_PIN   B6
#define PS2_DATA_PIN    F7
*/
#define CAPS_LED_PIN    B2