#undef MANUFACTURER
#undef VENDOR_ID
#undef PRODUCT

/* USB Device descriptor parameter */
#define VENDOR_ID       0x4B42
#define MANUFACTURER    datenpirat
#define PRODUCT         KBD75

#undef RGBLIGHT_ANIMATIONS
// #define RGBLIGHT_ANIMATIONS // save some space!
//#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_BREATHING
//#define RGBLIGHT_EFFECT_CHRISTMAS
//#define RGBLIGHT_EFFECT_KNIGHT
//#define RGBLIGHT_EFFECT_RAINBOW_MOOD
//#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
//#define RGBLIGHT_EFFECT_RGB_TEST
//#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
//#define RGBLIGHT_EFFECT_TWINKLE

#define RGBLIGHT_EFFECT_KNIGHT_LED_NUM 8
#define RGBLIGHT_EFFECT_KNIGHT_OFFSET 8
#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYER_BLINK

#define TAPPING_TERM            175
#define SEXYSHIFT_TERM          150
#define SEXYSHIFT_TAPPING_MIN_TERM  0
#define SEXYSHIFT_TAPPING_MAX_TERM  125
#define RGB_ACK_BLINK_TIME      500
#define RGB_ACK_ON_LAYER        5
#define RGB_ACK_OFF_LAYER       6

//#define NO_ACTION_ONESHOT
