
#define RGBLIGHT_EFFECT_KNIGHT_LED_NUM 8
#define RGBLIGHT_EFFECT_KNIGHT_OFFSET 8
#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYER_BLINK

#define TAPPING_TERM            175
#define SEXYSHIFT_TERM          150
#define SEXYSHIFT_TAPPING_MIN_TERM  0
#define SEXYSHIFT_TAPPING_MAX_TERM  125
#define RGB_ACK_BLINK_TIME      500
#define RGB_ACK_ON_LAYER        5
#define RGB_ACK_OFF_LAYER       6

//#define NO_ACTION_ONESHOT
