# datenpirat features
AUTO_SHIFT_ENABLE = yes
# DYNAMIC_MACRO_ENABLE = no
TAP_DANCE_ENABLE=yes
#RAW_ENABLE = yes
# COMBO_ENABLE = yes
# CONSOLE_ENABLE = yes
# NKRO_ENABLE = yes
# RGBLIGHT_ENABLE = no
